# Get scraped scotus data

We scraped the scotus docket data for all dockets between 2001 and 2024, to the extent they are available on the scotus website.

This notebook outlines the steps undertook to parse relevant information from the scraped pages for linking the appellate chain (scotus to the lower court). The final output is scotus_data.csv

# Import libraries

In [1]:
import os

import numpy as np
import pandas as pd

from parse_utils import parse_scotus_file

# Use the helper functions to get the data & clean as needed

In [2]:
%%time

root_folder = "scotus_dockets/scraped_A/"
count = 0
jsons = []

for dirpath, dirnames, filenames in os.walk(root_folder):
    # Clean up subdirectories
    dirnames[:] = [d for d in dirnames if not d.endswith('.ipynb_checkpoints') and not d.endswith('.DS_Store')]

    # Skip files ending with .ipynb_checkpoints
    filenames = [f for f in filenames if not f.endswith('.ipynb_checkpoints') and not f.endswith('.DS_Store')]
    if not filenames:
        continue

    # Get current folder name
    folder_name = os.path.basename(dirpath)
    json_filename = f"data/scraped_scotus_A/{folder_name}.json"
    print("--- Processing folder:", folder_name)

    results = {}
    for filename in filenames:
        file_path = os.path.join(dirpath, filename)
        results[filename] = parse_scotus_file(file_path)
        count += 1

    df = pd.DataFrame.from_dict(results, orient='index').reset_index().rename(columns={'index': 'filename'})
    df.to_json(json_filename)
    jsons.append(f"{folder_name}.json")
    print(f"Saved results to: {json_filename}")

print(f"\nProcessed {count} files and saved JSONs: {', '.join(sorted(jsons))}")

--- Processing folder: 03
Saved results to: data/scraped_scotus_A/03.json
--- Processing folder: 04
Saved results to: data/scraped_scotus_A/04.json
--- Processing folder: 05
Saved results to: data/scraped_scotus_A/05.json
--- Processing folder: 02
Saved results to: data/scraped_scotus_A/02.json
--- Processing folder: 20
Saved results to: data/scraped_scotus_A/20.json
--- Processing folder: 18
Saved results to: data/scraped_scotus_A/18.json
--- Processing folder: 11
Saved results to: data/scraped_scotus_A/11.json
--- Processing folder: 16
Saved results to: data/scraped_scotus_A/16.json
--- Processing folder: 17
Saved results to: data/scraped_scotus_A/17.json
--- Processing folder: 10
Saved results to: data/scraped_scotus_A/10.json
--- Processing folder: 19
Saved results to: data/scraped_scotus_A/19.json
--- Processing folder: 21
Saved results to: data/scraped_scotus_A/21.json
--- Processing folder: 07
Saved results to: data/scraped_scotus_A/07.json
--- Processing folder: 09
Saved results to: data/scraped_scotus_A/09.json
--- Processing folder: 08
Saved results to: data/scraped_scotus_A/08.json
--- Processing folder: 01
Saved results to: data/scraped_scotus_A/01.json
--- Processing folder: 06
Saved results to: data/scraped_scotus_A/06.json
--- Processing folder: 24
Saved results to: data/scraped_scotus_A/24.json
--- Processing folder: 23
Saved results to: data/scraped_scotus_A/23.json
--- Processing folder: 15
Saved results to: data/scraped_scotus_A/15.json
--- Processing folder: 12
Saved results to: data/scraped_scotus_A/12.json
--- Processing folder: 13
Saved results to: data/scraped_scotus_A/13.json
--- Processing folder: 14
Saved results to: data/scraped_scotus_A/14.json
--- Processing folder: 22
Saved results to: data/scraped_scotus_A/22.json

Processed 25831 files and saved JSONs: 01.json, 02.json, 03.json, 04.json, 05.json, 06.json, 07.json, 08.json, 09.json, 10.json, 11.json, 12.json, 13.json, 14.json, 15.json, 16.json, 17.json, 18.json, 19.json, 20.json, 21.json, 22.json, 23.json, 24.json
CPU times: user 2min 10s, sys: 1.45 s, total: 2min 11s
Wall time: 2min 16s

# Combine the individual csvs for each year into one large csv

In [3]:
df_list = []

for json_file in jsons:
    df = pd.read_json(f"data/scraped_scotus_A/{json_file}")
    df_list.append(df)

# Combine all DataFrames
scotus_df = pd.concat(df_list, ignore_index=True)

# Rename the case_number column
scotus_df = scotus_df.rename(columns={'case_number': 'docket_number'})

# Get the year and case id for the particular year
scotus_df["year"] = scotus_df["docket_number"].str.split("A").str[0]
scotus_df["case_num"] = scotus_df["docket_number"].str.split("A").str[1].astype(int)

len(scotus_df)

25831

In [4]:
scotus_df.head()

,filename,docket_number,docket_date,case_title,lower_court,lower_court_case_numbers_raw,lower_court_case_numbers,lower_court_decision_date,lower_court_rehearing_denied_date,year,case_num
0,03A517.htm,03A517,NaN,"Randy Kailey, Applicant v. Colorado",Court of Appeals of Colorado,"(01CA1378, 01CA2294)","01CA1378, 01CA2294",NaN,NaN,03,517
1,03A271.htm,03A271,NaN,"Christie M. Browne, Applicant v. John D. Ashcr...",United States Court of Appeals for the Fifth C...,(03-60138),03-60138,NaN,NaN,03,271
2,03A265.htm,03A265,NaN,"Dameon Sean White, Applicant v. California","Court of Appeal of California, Fifth Appellate...",(F039132),F039132,NaN,NaN,03,265
3,03A503.htm,03A503,NaN,"James E. Reid, Applicant v. Page True, Warden",United States Court of Appeals for the Fourth ...,"(02-27, 03-2)","02-27, 03-2",NaN,NaN,03,503
4,03A259.htm,03A259,NaN,"Stephan A. Bitterman, Individually, and as Per...",Supreme Court of Florida,(SC03-1059),SC03-1059,NaN,NaN,03,259

# Confirm case numbers are bound between 1-2000 for all years

In [5]:
# Define valid bounds
lower_range = (1, 2000)

# Function to check if all case numbers fall within the allowed ranges
def is_year_valid(series):
    return series.dropna().apply(
        lambda x: lower_range[0] <= x <= lower_range[1]).all()

# Group by year and check validity
validity_by_year = scotus_df.groupby("year")["case_num"].apply(is_year_valid)
invalid_years = validity_by_year[~validity_by_year]

assert invalid_years.empty

# Check for years where the max for each range might have been cut off

In [6]:
upper_range = (1, 2000)

grouped = scotus_df.groupby("year")

upper_max = grouped.apply(lambda g: g.loc[g["case_num"].between(*upper_range), "case_num"].max())
upper_max

/var/folders/d9/3h7m7wc52kv6fgxmbyd8s0940000gn/T/ipykernel_83741/3779466430.py:5: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  upper_max = grouped.apply(lambda g: g.loc[g["case_num"].between(*upper_range), "case_num"].max())

year
01     861
02    1097
03    1065
04    1081
05    1236
06    1243
07    1044
08    1167
09    1268
10    1277
11    1256
12    1251
13    1286
14    1313
15    1303
16    1269
17    1425
18    1369
19    1071
20     178
21     876
22    1131
23    1177
24    1295
dtype: int64

# Confirm no missing docket numbers

In [7]:
assert len(scotus_df[scotus_df["docket_number"].isna()]) == 0

# Confirm no duplicate docket numbers

In [8]:
assert len(scotus_df[scotus_df.duplicated(subset=['docket_number'])]) == 0

# Confirm no missing case titles

In [9]:
assert len(scotus_df[scotus_df["case_title"].isnull()]) == 0

# Check for number of missing lower court name or lower court case numbers for each year

Manually verify a sample of those with lower court but without lower court case numbers is due to missing lower court case number info from scotus

In [10]:
scotus_df[(~scotus_df["lower_court"].isnull()) & (scotus_df["lower_court_case_numbers_raw"].isnull())]

,filename,docket_number,docket_date,case_title,lower_court,lower_court_case_numbers_raw,lower_court_case_numbers,lower_court_decision_date,lower_court_rehearing_denied_date,year,case_num
83,03A879.htm,03A879,NaN,"Margaret Bagley, Warden, Applicant v. Gregory ...",United States Court of Appeals for the Sixth C...,None,None,NaN,NaN,03,879
155,03A317.htm,03A317,NaN,"Robert Freeman, Applicant v. Pennsylvania","Supreme Court of Pennsylvania, Eastern District",None,None,NaN,NaN,03,317
860,03A247.htm,03A247,NaN,"Jose Martinez, Jr., Applicant v. United States",United States Court of Appeals for the Ninth C...,None,None,NaN,NaN,03,247
946,03A120.htm,03A120,NaN,"George T. Loebe, Sr., Applicant v. Glenn R. Fi...",Supreme Court of South Carolina,None,None,NaN,NaN,03,120
1800,04A1078.htm,04A1078,NaN,"United States, Applicant v. Sean Lamont Cromer",United States Court of Appeals for the Sixth C...,None,None,NaN,NaN,04,1078
2493,05A83.htm,05A83,NaN,"Donald J. Strable, Applicant v. South Carolina",Supreme Court of South Carolina,None,None,NaN,NaN,05,83
2853,05A920.htm,05A920,NaN,"Wilma Rowell-Poston, Applicant v. Florence Cou...",Supreme Court of South Carolina,None,None,NaN,NaN,05,920
2894,05A467.htm,05A467,NaN,"Shawn Paul Humphries, Applicant v. South Carolina",Supreme Court of South Carolina,None,None,NaN,NaN,05,467
3137,05A980.htm,05A980,NaN,"Janet Lutkewitte, Applicant v. Alberto R. Gonz...",United States Court of Appeals for the Distric...,None,None,NaN,NaN,05,980
3463,02A572.htm,02A572,NaN,"Kenneth Ford, Applicant v. Pennsylvania","Supreme Court of Pennsylvania, Eastern District",None,None,None,NaN,02,572
3655,20A79.json,20A79,2020-10-30,"Gary Victor Dubin, Applicant v. Office of Disc...",Supreme Court of Hawaii,None,None,NaN,NaN,20,79
3807,20A98.json,20A98,2020-12-03,"Mike Kelly, United States Congressman, et al.,...","Supreme Court of Pennsylvania, Middle District",None,None,NaN,NaN,20,98
3923,18A444.json,18A444,2018-10-26,"Troy Sierra, Applicant v. Julie L. Jones, Secr...",United States Court of Appeals for the Elevent...,None,None,NaN,NaN,18,444
4456,18A1279.json,18A1279,2019-06-06,"Miles Christian-Hart, Applicant v. Wells Fargo...","District Court of Appeal of Florida, Second Di...",None,None,NaN,NaN,18,1279
5197,11A406.htm,11A406,None,"Marie Assa'ad-Faltas, Applicant v. City of Col...",Supreme Court of South Carolina,None,None,None,NaN,11,406
5655,11A891.htm,11A891,2012-03-22,"Mr. S., Applicant v. United States",United States Court of Appeals for the First C...,None,None,None,NaN,11,891
6147,11A553.htm,11A553,None,"Marie Assa'ad-Faltas, Applicant v. Barney Gies...",Supreme Court of South Carolina,None,None,None,NaN,11,553
7415,16A1247.html,16A1247,2017-06-20,"Summer Lynn Leon, Applicant v. Arizona",Supreme Court of Arizona,None,None,None,NaN,16,1247
9772,10A253.htm,10A253,None,"Marie Assa'ad-Faltas, Applicant v. South Carolina",Supreme Court of South Carolina,None,None,None,NaN,10,253
10116,10A22.htm,10A22,None,"Don Boyd, Applicant v. Wal-Mart Stores, Inc., ...",Supreme Court of South Carolina,None,None,None,NaN,10,22
10150,10A386.htm,10A386,None,"J. Doe, Applicant v. Richard L. Duncan, et al.",Supreme Court of South Carolina,None,None,None,NaN,10,386
11438,19A627.json,19A627,2019-12-05,"Alvin Fulton, Applicant v. New York",Court of Appeals of New York,None,None,NaN,NaN,19,627
11696,21A225.json,21A225,2021-12-14,"Larry Klayman, Applicant v. Judicial Watch, In...",United States Court of Appeals for the Distric...,None,None,NaN,NaN,21,225
13075,07A956.htm,07A956,NaN,"Curtis Osborne, Applicant v. Georgia","Superior Court of Georgia, Butts County",None,None,None,NaN,07,956
13595,09A24.htm,09A24,NaN,"Eric Taylor, et ux., Applicant v. National Cit...",Supreme Court of Indiana,None,None,NaN,NaN,09,24
13669,09A216.htm,09A216,NaN,"Eric Taylor, et ux., Applicants v. National Ci...",Supreme Court of Indiana,None,None,NaN,NaN,09,216
13797,09A886.htm,09A886,NaN,"J. Doe, Applicant v. Richard L. Duncan, et al.",Supreme Court of South Carolina,None,None,NaN,NaN,09,886
13957,09A117.htm,09A117,NaN,"Anthony Foster, Applicant v. New York",Court of Appeals of New York,None,None,NaN,NaN,09,117
14273,09A692.htm,09A692,NaN,"Douglas J. Raymond, Applicant v. Supreme Court...",Supreme Court of Ohio,None,None,NaN,NaN,09,692
14675,08A954.htm,08A954,NaN,"Mark A. Cassell, Applicant v. Adam Toler Memor...","Circuit Court of West Virginia, Wyoming County",None,None,NaN,NaN,08,954
14791,08A942.htm,08A942,NaN,"Thomas Treshawn Ivey, Applicant v. Jon Ozmint,...",Supreme Court of South Carolina,None,None,NaN,NaN,08,942
15679,08A797.htm,08A797,NaN,"Robert Newland, Applicant v. Georgia","Superior Court of Georgia, Butts County",None,None,NaN,NaN,08,797
17243,24A1221.json,24A1221,2025-06-11,"Kimberly King, Applicant v. Thomas Hasle, et al.",United States Court of Appeals for the Seventh...,None,None,NaN,NaN,24,1221
18427,23A997.json,23A997,2024-05-08,"Sealed Appellant, Applicant v. Paul Burgermeis...",United States Court of Appeals for the Seventh...,None,None,NaN,NaN,23,997
19114,23A696.json,23A696,2024-01-26,"Students for Fair Admissions, Inc. Applicant v...",United States District Court for the Southern ...,None,None,NaN,NaN,23,696
20119,15A95.htm,15A95,2015-07-22,"Joseph DiBruno, Jr., Applicant v. United States",United States Court of Appeals for the Fourth ...,None,None,None,NaN,15,95
20803,15A1091.htm,15A1091,2016-04-21,"Harischandra Khemlall, Applicant v. Loretta E....",United States Court of Appeals for the Second ...,None,None,None,NaN,15,1091
21023,12A662.htm,12A662,2012-12-28,"Alfred White, Applicant v. Vimal Singh, Warden",United States Court of Appeals for the Ninth C...,None,None,None,NaN,12,662
21853,12A31.htm,12A31,2012-07-10,"Victor Quiles, Applicant v. New York",Court of Appeals of New York,None,None,None,NaN,12,31
22051,12A132.htm,12A132,2012-08-07,"Paul Ruine, Applicant v. New York",Court of Appeals of New York,None,None,None,NaN,12,132
22129,13A311.htm,13A311,2013-09-27,"Hashim Matthews, Applicant v. New York",Court of Appeals of New York,None,None,None,NaN,13,311
22180,13A299.htm,13A299,2013-09-24,"Timothy Patrick Chambers, Applicant v. Minnesota",Supreme Court of Minnesota,None,None,None,NaN,13,299
22514,13A832.htm,13A832,2014-02-12,"Joseph Elliott, Applicant v. Pennsylvania","Supreme Court of Pennsylvania, Eastern District",None,None,None,NaN,13,832
22671,13A1276.htm,13A1276,None,"Cynthia E. Collie, Applicant v. South Carolina...",Supreme Court of South Carolina,None,None,None,NaN,13,1276
23313,13A719.htm,13A719,2014-01-09,"Michael Miran, Applicant v. New York",Court of Appeals of New York,None,None,None,NaN,13,719
24021,14A875.htm,14A875,2015-02-19,"Florida, Applicant v. Jerry William Correll",Supreme Court of Florida,None,None,NaN,NaN,14,875

Confirm the only instance where we have the lower court case number but did not have the lower court was due to missing info from scotus

In [11]:
scotus_df[(scotus_df["lower_court"].isnull()) & (~scotus_df["lower_court_case_numbers_raw"].isnull())]

,filename,docket_number,docket_date,case_title,lower_court,lower_court_case_numbers_raw,lower_court_case_numbers,lower_court_decision_date,lower_court_rehearing_denied_date,year,case_num
25216,22A1115.json,22A1115,2023-06-23,"In Re Sealed Case, Applicant v.",None,(),,NaN,NaN,22,1115

Confirm majority of the cases with missing lower court information are cases "In Re"

In [12]:
subset = scotus_df[scotus_df["lower_court_case_numbers_raw"].isnull()]
starts_with_in_re = subset["case_title"].str.startswith("In Re")

num_in_re = starts_with_in_re.sum()
num_not_in_re = (~starts_with_in_re).sum()

print(f"Num Cases that start with 'In Re': {num_in_re} / {len(subset)}")
print(f"Num Cases that do NOT start with 'In Re': {num_not_in_re} / {len(subset)}")

Num Cases that start with 'In Re': 278 / 352
Num Cases that do NOT start with 'In Re': 74 / 352

Manually verify a sample of those without lower court and not In Re cases is due to missing lower court info from scotus

In [13]:
subset[~starts_with_in_re]

,filename,docket_number,docket_date,case_title,lower_court,lower_court_case_numbers_raw,lower_court_case_numbers,lower_court_decision_date,lower_court_rehearing_denied_date,year,case_num
83,03A879.htm,03A879,NaN,"Margaret Bagley, Warden, Applicant v. Gregory ...",United States Court of Appeals for the Sixth C...,None,None,NaN,NaN,03,879
155,03A317.htm,03A317,NaN,"Robert Freeman, Applicant v. Pennsylvania","Supreme Court of Pennsylvania, Eastern District",None,None,NaN,NaN,03,317
260,03A249.htm,03A249,NaN,"John Doe, Applicant v. United States",None,None,None,NaN,NaN,03,249
417,03A26.htm,03A26,NaN,"In re Riley D. Noel, Applicant v.",None,None,None,NaN,NaN,03,26
502,03A982.htm,03A982,NaN,"Daniel Benitez, Applicant v. John Mata",None,None,None,NaN,NaN,03,982
...,...,...,...,...,...,...,...,...,...,...,...
24825,22A431.json,22A431,2022-11-15,"Murray Hooper, Applicant v. David Shinn, et al.",None,None,None,NaN,NaN,22,431
24966,22A447.json,22A447,2022-11-21,"Bradly Cunningham, Applicant v. Oregon",None,None,None,NaN,NaN,22,447
25255,22A334.json,22A334,2022-10-20,"Oscar Stilley, Applicant v. United States",None,None,None,NaN,NaN,22,334
25346,22A439.json,22A439,2022-11-16,"Richard Fairchild, Applicant v. Jim Farris, W...",None,None,None,NaN,NaN,22,439
25522,22A834.json,22A834,2023-03-22,"Zumar DuBose, Applicant v. United States",None,None,None,NaN,NaN,22,834

# Save the data for future use

In [14]:
scotus_df.to_json("data/scotus_data_A.json")

In [15]:
len(scotus_df)

25831